[project]
name = "chatbotqwen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bell", email = "guizadinho2@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "openai>=3.19.2",
    "pywin32>=312",
]

[project.scripts]
chatbotqwen = "chatbotqwen:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
